# Generated by Django 4.2.19 on 2025-02-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_order_alter_shippingaddress_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipped",
            field=models.BooleanField(default=False),
        ),
    ]
